# Generated by Django 2.1.2 on 2019-03-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, max_length=2000)),
                ('creation_date', models.DateField(default='2019-03-06')),
                ('due_date', models.DateField(default='2019-03-06')),
            ],
        ),
    ]
