# Generated by Django 2.1.2 on 2019-03-06 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='due_time',
            field=models.TimeField(default=datetime.time(19, 25, 54, 916086)),
        ),
    ]
