# Generated by Django 2.1.2 on 2019-03-06 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20190307_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='id',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_time',
            field=models.TimeField(default=datetime.time(19, 46, 56, 675465)),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
