# Generated by Django 2.1.2 on 2019-03-06 21:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20190307_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='due_time',
            field=models.TimeField(default=datetime.time(21, 27, 24, 614587)),
        ),
    ]
